### ISSUE TITLE
可否添加一个人脸检测自动点击的功能呢？

### ISSUE THREAD

**Issue by JerryChenn07** [rockswang/bjjnts.cn#1]
同性交友网站终于恢复了响应了。

感谢大佬，比我写的模拟点击功能强太多了。您这功能太强了，无奈js不太会用，想着来github上瞅瞅，就发现了这个，于是就懒了。。。

建议：加一个人脸检测时模拟点击的功能(有时候就是做电脑前，随便他检测呢)，这样感觉更逼真了。可以增加说明，让使用人员可以根据需要选择是否注释掉此功能。

**Comment by rockswang** [comment]
确实发现有时候人脸检测对话框直接hide关不掉的情况，不过我这里很少复现，我加了个自动点击按钮的机制，也不知道是否起作用。
反正我这儿基本可以保持一直刷课，凑合用吧，呵呵。

**Comment by JerryChenn07** [comment]
thanks
